// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFekouu5aiTVUY0Zkrxc1o4ukoMbiHk-w',
    appId: '1:257151842419:web:cae63029d3db4ffc48d206',
    messagingSenderId: '257151842419',
    projectId: 'kbuiot-bce2a',
    authDomain: 'kbuiot-bce2a.firebaseapp.com',
    storageBucket: 'kbuiot-bce2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6mqxv5tPX-RuJy1Adk0MQHgU5SfhIdhE',
    appId: '1:257151842419:android:c022c4d8ea6befde48d206',
    messagingSenderId: '257151842419',
    projectId: 'kbuiot-bce2a',
    storageBucket: 'kbuiot-bce2a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqTNtbylW1TDsO4ljT8mM64EjOzNUCjc',
    appId: '1:257151842419:ios:30a787ab9377cf8848d206',
    messagingSenderId: '257151842419',
    projectId: 'kbuiot-bce2a',
    storageBucket: 'kbuiot-bce2a.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqTNtbylW1TDsO4ljT8mM64EjOzNUCjc',
    appId: '1:257151842419:ios:30a787ab9377cf8848d206',
    messagingSenderId: '257151842419',
    projectId: 'kbuiot-bce2a',
    storageBucket: 'kbuiot-bce2a.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFekouu5aiTVUY0Zkrxc1o4ukoMbiHk-w',
    appId: '1:257151842419:web:874a0079544fdf2f48d206',
    messagingSenderId: '257151842419',
    projectId: 'kbuiot-bce2a',
    authDomain: 'kbuiot-bce2a.firebaseapp.com',
    storageBucket: 'kbuiot-bce2a.firebasestorage.app',
  );

}